version: "3.9"

services:
  nginx:
    container_name: browser-app-nginx
    image: nginx:latest
    restart: always
    ports:
      - "${BROWSER_APP_BIND_ADDR:-127.0.0.1}:${BROWSER_APP_PORT:-8080}:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www-root:/browser-app
  