version: '3.3'
services:
  bitcoind:
    image: polarlightning/bitcoind:24.0
    container_name: clams-bitcoind
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: bitcoind
    command: >-
      bitcoind -server=1 -regtest=${IS_REGTEST} -testnet=${IS_TESTNET} -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526 -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28334 -zmqpubrawtx=tcp://0.0.0.0:28335 -zmqpubhashblock=tcp://0.0.0.0:28336 -txindex=1 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcport=${BITCOIND_RPC_PORT} -rest -listen=1 -listenonion=0 -fallbackfee=0.0002
    volumes:
      - ./volumes/bitcoind:/home/bitcoin/.bitcoin
    expose:
      - '${BITCOIND_RPC_PORT:-18443}'
      - '18444'
      - '28334'
      - '28335'
    ports:
      - '${BITCOIND_RPC_PORT:-18443}:${BITCOIND_RPC_PORT:-18443}'
      - '${BITCOIND_P2P_PORT:-19444}:18444'
      - '127.0.0.1:28334:28334'
      - '127.0.0.1:29335:28335'

  clightning:
    image: polarlightning/clightning:22.11
    container_name: clams-clightning
    hostname: clightning
    command: >-
      lightningd --alias=clightning-${BTC_CHAIN:-regtest} --addr=clightning --announce-addr=${WEBSOCKET_BIND_ADDR:-127.0.0.1}:${WEBSOCKET_PORT:-9736} --network=${BTC_CHAIN:-regtest} --bitcoin-rpcuser=polaruser --bitcoin-rpcpassword=polarpass --bitcoin-rpcconnect=clams-bitcoind --bitcoin-rpcport=${BITCOIND_RPC_PORT} --log-level=info --dev-bitcoind-poll=20 --dev-fast-gossip --experimental-websocket-port=9736
    restart: always
    volumes:
      - ./volumes/clightning/lightningd:/home/clightning/.lightning
      - ./volumes/clightning/rest-api:/opt/c-lightning-rest/certs
    expose:
      - '8080'
      - '11001'
      - '9735'
      - '9736'
    ports:
      - '8181:8080'
      - '11001:11001'
      - '${P2P_BIND_ADDR:-127.0.0.1}:${P2P_PORT:-9736}:9735'
      - '${WEBSOCKET_BIND_ADDR:-127.0.0.1}:${WEBSOCKET_PORT:-9736}:9736'
