version: '3.8'
services:

  reverse-proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
      - "9736:9863"
    configs:
      - source: nginx-config
        target: /etc/nginx/nginx.conf
    volumes:
      - clams-browser-app:/browser-app
      - certs:/certs

  bitcoind:
    image: polarlightning/bitcoind:24.0
    hostname: bitcoind
    networks:
      - bitcoindnet
    command: >-
      bitcoind -server=1 -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526 -zmqpubrawblock=tcp://0.0.0.0:28334 -zmqpubrawtx=tcp://0.0.0.0:28335 -zmqpubhashblock=tcp://0.0.0.0:28336 -txindex=1 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcport=18443 -rest -listen=1 -listenonion=0 -fallbackfee=0.0002 -mempoolfullrbf=1 -regtest
    deploy:
      mode: replicated
      replicas: 1

  cln-0:
    image: roygbiv/cln:23.02.2
    hostname: cln-0
    command: >-
      sh -c "chown 1000:1000 /opt/c-lightning-rest/certs && lightningd --alias=cln-regtest --bind-addr=0.0.0.0 --announce-addr=${CLIGHTNING_LOCAL_BIND_ADDR:-localhost}:${CLIGHTNING_WEBSOCKET_EXTERNAL_PORT:-9736} --bitcoin-rpcuser=polaruser --bitcoin-rpcpassword=polarpass --bitcoin-rpcconnect=bitcoind --bitcoin-rpcport=${BITCOIND_RPC_PORT:-18443} --log-level=debug --dev-bitcoind-poll=20 --dev-fast-gossip --experimental-websocket-port=9736 --plugin=/opt/c-lightning-rest/plugin.js --experimental-offers --network=regtest --network=regtest --network=regtest"
    volumes:
      - cln-0:/home/clightning/.lightning
      - cln-0-certs:/opt/c-lightning-rest/certs
    networks:
      - bitcoindnet
      - clnnet-0
    deploy:
      mode: replicated
      replicas: 1

networks:
  bitcoindnet:
  clnnet-0:

volumes:

  bitcoind:
    external: true
    name: bitcoind-regtest
  cln-0:
  cln-0-certs:

  clams-browser-app:
    external: true
    name: clams-browser-app
  certs:
    external: true
    name: clams-certs

configs:
  nginx-config:
    file: /home/farscapian/github/farscapian/clams-app-docker/backend/nginx.conf

